/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticRouteImport } from './routes/_authenticated/diagnostic'
import { Route as AuthenticatedGapsRouteImport } from './routes/_authenticated/gaps'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedSkillDnaRouteImport } from './routes/_authenticated/skill-dna'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedBridgeNodeIdRouteImport } from './routes/_authenticated/bridge.$nodeId'
import { Route as AuthenticatedInterviewSessionIdRouteImport } from './routes/_authenticated/interview_.$sessionId'
import { Route as AuthenticatedPracticeNodeIdRouteImport } from './routes/_authenticated/practice.$nodeId'
import { Route as AuthenticatedInterviewSessionIdResultsRouteImport } from './routes/_authenticated/interview_.$sessionId_.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticRoute = AuthenticatedDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGapsRoute = AuthenticatedGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillDnaRoute = AuthenticatedSkillDnaRouteImport.update({
  id: '/skill-dna',
  path: '/skill-dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBridgeNodeIdRoute =
  AuthenticatedBridgeNodeIdRouteImport.update({
    id: '/bridge/$nodeId',
    path: '/bridge/$nodeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionIdRoute =
  AuthenticatedInterviewSessionIdRouteImport.update({
    id: '/interview_/$sessionId',
    path: '/interview/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeNodeIdRoute =
  AuthenticatedPracticeNodeIdRouteImport.update({
    id: '/practice/$nodeId',
    path: '/practice/$nodeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionIdResultsRoute =
  AuthenticatedInterviewSessionIdResultsRouteImport.update({
    id: '/interview_/$sessionId_/results',
    path: '/interview/$sessionId/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/skill-dna': typeof AuthenticatedSkillDnaRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/bridge/$nodeId': typeof AuthenticatedBridgeNodeIdRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/practice/$nodeId': typeof AuthenticatedPracticeNodeIdRoute
  '/interview/$sessionId/results': typeof AuthenticatedInterviewSessionIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/skill-dna': typeof AuthenticatedSkillDnaRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/bridge/$nodeId': typeof AuthenticatedBridgeNodeIdRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/practice/$nodeId': typeof AuthenticatedPracticeNodeIdRoute
  '/interview/$sessionId/results': typeof AuthenticatedInterviewSessionIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/_authenticated/gaps': typeof AuthenticatedGapsRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/skill-dna': typeof AuthenticatedSkillDnaRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/bridge/$nodeId': typeof AuthenticatedBridgeNodeIdRoute
  '/_authenticated/interview_/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/_authenticated/practice/$nodeId': typeof AuthenticatedPracticeNodeIdRoute
  '/_authenticated/interview_/$sessionId_/results': typeof AuthenticatedInterviewSessionIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diagnostic'
    | '/gaps'
    | '/interview'
    | '/plan'
    | '/skill-dna'
    | '/tutor'
    | '/bridge/$nodeId'
    | '/interview/$sessionId'
    | '/practice/$nodeId'
    | '/interview/$sessionId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diagnostic'
    | '/gaps'
    | '/interview'
    | '/plan'
    | '/skill-dna'
    | '/tutor'
    | '/bridge/$nodeId'
    | '/interview/$sessionId'
    | '/practice/$nodeId'
    | '/interview/$sessionId/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostic'
    | '/_authenticated/gaps'
    | '/_authenticated/interview'
    | '/_authenticated/plan'
    | '/_authenticated/skill-dna'
    | '/_authenticated/tutor'
    | '/_authenticated/bridge/$nodeId'
    | '/_authenticated/interview_/$sessionId'
    | '/_authenticated/practice/$nodeId'
    | '/_authenticated/interview_/$sessionId_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic': {
      id: '/_authenticated/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof AuthenticatedDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gaps': {
      id: '/_authenticated/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AuthenticatedGapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-dna': {
      id: '/_authenticated/skill-dna'
      path: '/skill-dna'
      fullPath: '/skill-dna'
      preLoaderRoute: typeof AuthenticatedSkillDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bridge/$nodeId': {
      id: '/_authenticated/bridge/$nodeId'
      path: '/bridge/$nodeId'
      fullPath: '/bridge/$nodeId'
      preLoaderRoute: typeof AuthenticatedBridgeNodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview_/$sessionId': {
      id: '/_authenticated/interview_/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/$nodeId': {
      id: '/_authenticated/practice/$nodeId'
      path: '/practice/$nodeId'
      fullPath: '/practice/$nodeId'
      preLoaderRoute: typeof AuthenticatedPracticeNodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview_/$sessionId_/results': {
      id: '/_authenticated/interview_/$sessionId_/results'
      path: '/interview/$sessionId/results'
      fullPath: '/interview/$sessionId/results'
      preLoaderRoute: typeof AuthenticatedInterviewSessionIdResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticRoute: typeof AuthenticatedDiagnosticRoute
  AuthenticatedGapsRoute: typeof AuthenticatedGapsRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedSkillDnaRoute: typeof AuthenticatedSkillDnaRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedBridgeNodeIdRoute: typeof AuthenticatedBridgeNodeIdRoute
  AuthenticatedInterviewSessionIdRoute: typeof AuthenticatedInterviewSessionIdRoute
  AuthenticatedPracticeNodeIdRoute: typeof AuthenticatedPracticeNodeIdRoute
  AuthenticatedInterviewSessionIdResultsRoute: typeof AuthenticatedInterviewSessionIdResultsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticRoute: AuthenticatedDiagnosticRoute,
  AuthenticatedGapsRoute: AuthenticatedGapsRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedSkillDnaRoute: AuthenticatedSkillDnaRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedBridgeNodeIdRoute: AuthenticatedBridgeNodeIdRoute,
  AuthenticatedInterviewSessionIdRoute: AuthenticatedInterviewSessionIdRoute,
  AuthenticatedPracticeNodeIdRoute: AuthenticatedPracticeNodeIdRoute,
  AuthenticatedInterviewSessionIdResultsRoute:
    AuthenticatedInterviewSessionIdResultsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
